# Generated by Django 4.2.30 on 2026-04-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_attendancerecord_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='hit_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='hit_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='hit_3',
            field=models.BooleanField(default=False),
        ),
    ]
